metadata.format.version = "1.1"

[versions]

velocity = "3.3.0-SNAPSHOT"
paper = "1.20.4-R0.1-SNAPSHOT"
miniplaceholders = "2.2.3"
fastlogin = "1.12-SNAPSHOT"
authme = "5.6.0"
libby = "1.3.1"
pluginyml = "0.6.0"
bstats = "3.1.0"
shadow = "8.1.1"
configurate = "4.1.2"
adventure = "4.18.0"
blossom = "2.1.0"
geantyref = "1.3.13"
indra = "3.1.3"
runtask = "2.3.1"
vpacketevents = "1.1.0"
luckperms = "5.4"

# Test versions
assertj = "3.27.2"

[libraries]

adventure = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
velocity-proxy = { group = "com.velocitypowered", name = "velocity-proxy", version.ref = "velocity" }
authme = { module = "fr.xephi:authme", version.ref = "authme" }

libby-core = { group = "net.byteflux", name = "libby-core", version.ref = "libby" }
libby-bukkit = { group = "net.byteflux", name = "libby-bukkit", version.ref = "libby" }
libby-paper = { group = "net.byteflux", name = "libby-paper", version.ref = "libby" }
libby-velocity = { group = "net.byteflux", name = "libby-velocity", version.ref = "libby" }

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }
vpacketevents = { group = "io.github.4drian3d", name = "vpacketevents-api", version.ref = "vpacketevents" }
luckperms = { module = "net.luckperms:api", version.ref = "luckperms" }

fastlogin-velocity = { group = "com.github.games647", name = "fastlogin.velocity", version.ref = "fastlogin" }
bstats-velocity = { group = "org.bstats", name = "bstats-velocity", version.ref = "bstats" }

configurate-hocon = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }

build-indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
build-indra-spotless = { module = "net.kyori:indra-licenser-spotless", version.ref = "indra" }
plugin-shadow = { group = "com.github.johnrengelman", name = "shadow", version.ref = "shadow" }

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]

pluginyml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "pluginyml" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
indra = { id = "net.kyori.indra.publishing", version.ref = "indra" }

runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.1.9" }
